default:
    just --list

# install dependencies
install:
    poetry install

# set up `pre-commit` hook
install-pre-commit:
    poetry run pre-commit install
    poetry run pre-commit install --hook-type commit-msg

# run app in the DEV mode
dev:
    poetry run fastapi dev src/main.py

# run app in the PROD mode
prod:
   poetry run fastapi run src/main.py

# create autogenerated alembic revision
mm *args:
  poetry run alembic revision --autogenerate -m "{{args}}"

# run migrations
migrate:
  poetry run alembic upgrade head

# downgrade migrations
downgrade *args:
  poetry run alembic downgrade {{args}}

# lint the code with ruff with autofix
lint:
    poetry run ruff src tests --fix

# check lint rules violation
lint-c:
    poetry run ruff check src tests

# format the code with ruff
fmt:
    poetry run ruff format src tests

# run tests with pytest
test *args:
    poetry run pytest tests {{args}}

# run only integration tests
test-i *args:
    poetry run pytest tests/integration {{args}}

# run only unit tests
test-u *args:
    poetry run pytest tests/unit {{args}}

# measure code coverage
test-cov *args:
    poetry run pytest --cov=src tests/

# start and run services with docker-compose
up:
  docker-compose up -d

# stop and remove containers, networks...
down:
  docker-compose down

# kills all services
kill *args:
  docker-compose kill {{args}}

# builds containers
build:
  docker-compose build

# list containers
ps:
  docker-compose ps